### PR TITLE
Bug/select contact and view contact details deselect contacts and feature/show only contact tab.

### PR DESCRIPTION
**Pull request by LeonardooBorges**
Issues #20 #26 done.

Hi @1gravity, I really appreciate your work in this lib and it helped me very much. I fixed some bugs and problems and want to contribute, so I opened this PR. .

As the issues says, I fixed the problem of selecting contacts and then opening a contact details gets all previous contacts to be deselected. I also added an option to allow showing only the contacts tab (hide the group one).

I also added an option to get the map containing all the phone numbers, emails and addresses as well as documentation.

I expect your review.

### CODE REVIEW

**Comment by 1gravity** [comment]
Thank you very much for your contribution. This looks really great. I especially like all the added documentation and reformatting of some of the code. I haven't tested it though but will do so on the weekend before I merge it.

One question though, why did you change the default values in the ContactImpl.java to empty string for the getter methods?

**Comment by LeonardooBorges** [comment]
Hello @1gravity I really appreciate that you liked the PR. I changed to empty strings because if someone calls that method, with a `TYPE_MOBILE` code by example, and it returns something, this person will assume that this return really is a mobile phone number, but in the way it was, the method was returning any number if the type sent wasn't present. I can remove the `&& !mEmail.isEmpty()` in the if also. But nevertheless if you want to change it back to the way it was, I can do that too.

**Comment by LeonardooBorges** [comment]
Hi @1gravity is there a prevision for the review? There are some projects in the company I work that would use this lib 😄

**Comment by binarybit10** [comment]
Hi,
I would also like to have the feature:  "show only contact tab"  (User has the option to disable Groups tab)  
@LeonardooBorges thanks for your merge. 

@1gravity I was looking for a project like this, your work is extremely useful, maybe I will have to wait for the merge to complete. 

Also, I'm seeing the same issue as listed in #28 
Thanks again - 👍 for the project :)

**Pull request merged**
